name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

  # conda-forge
  - numpy
  - matplotlib

  # Pip-only installs
  - pip:
    - qiskit==0.46.0
    - codecov
    - qiskit-nature
    - qiskit-algorithms
    - qiskit-aer
    - sphinx-rtd-theme

